
[[constraint]]
  name = "github.com/gravitational/teleport"
  version = "v2.3.5"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/gravitational/trace"
  version = "1.1.3"

[[constraint]]
  name = "github.com/fatih/color"
  version = "v1.5.0"

[[override]]
  name = "github.com/russellhaering/gosaml2"
  revision = "82a6e6132741c96a25969cec66912b6c24fcbd5f"

[[override]]
  name = "github.com/coreos/etcd"
  version="v3.2.4"

[[override]]
  name = "github.com/ugorji/go"
  #version = "v1.1"
  revision = "646ae4a518c1c3be0739df898118d9bccf993858"

[[override]]
  name = "github.com/tstranex/u2f"
  revision = "eb799ce68da4150b16ff5d0c89a24e2a2ad993d8"

[[override]]
  name = "golang.org/x/crypto"
  revision = "453249f01cfeb54c3d549ddb75ff152ca243f9d8"
